[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "20.11.1"

# Increase concurrent upload limit cautiously to avoid rate limit token errors
[functions]
  node_bundler = "esbuild"